import type { Equipment, Exercise, MuscleGroup } from "../../domain/fitness.ts";

function exercise(
  id: string,
  name: string,
  equipment: Equipment,
  muscleGroup: MuscleGroup,
): Exercise {
  return {
    id: `predefined:${id}`,
    name,
    equipment,
    muscleGroup,
    source: "predefined",
  };
}

export const predefinedExercises: Exercise[] = [
  exercise("goblet-squat", "Goblet Squat", "dumbbell", "legs"),
  exercise("dumbbell-squat", "Dumbbell Squat", "dumbbell", "legs"),
  exercise(
    "dumbbell-romanian-deadlift",
    "Dumbbell Romanian Deadlift",
    "dumbbell",
    "glutes",
  ),
  exercise("dumbbell-deadlift", "Dumbbell Deadlift", "dumbbell", "legs"),
  exercise(
    "dumbbell-bulgarian-split-squat",
    "Dumbbell Bulgarian Split Squat",
    "dumbbell",
    "legs",
  ),
  exercise(
    "dumbbell-reverse-lunge",
    "Dumbbell Reverse Lunge",
    "dumbbell",
    "legs",
  ),
  exercise("dumbbell-step-up", "Dumbbell Step-Up", "dumbbell", "legs"),
  exercise("dumbbell-calf-raise", "Dumbbell Calf Raise", "dumbbell", "legs"),
  exercise(
    "dumbbell-glute-bridge",
    "Dumbbell Glute Bridge",
    "dumbbell",
    "glutes",
  ),
  exercise(
    "monster-walk-band",
    "Monster Walk with Band",
    "resistance-band",
    "glutes",
  ),
  exercise("dumbbell-floor-press", "Dumbbell Floor Press", "dumbbell", "chest"),
  exercise("dumbbell-bench-press", "Dumbbell Bench Press", "dumbbell", "chest"),
  exercise(
    "incline-dumbbell-press",
    "Incline Dumbbell Press",
    "dumbbell",
    "chest",
  ),
  exercise("dumbbell-pullover", "Dumbbell Pullover", "dumbbell", "chest"),
  exercise(
    "dumbbell-shoulder-press",
    "Dumbbell Shoulder Press",
    "dumbbell",
    "shoulders",
  ),
  exercise("arnold-press", "Arnold Press", "dumbbell", "shoulders"),
  exercise(
    "dumbbell-lateral-raise",
    "Dumbbell Lateral Raise",
    "dumbbell",
    "shoulders",
  ),
  exercise(
    "dumbbell-front-raise",
    "Dumbbell Front Raise",
    "dumbbell",
    "shoulders",
  ),
  exercise(
    "dumbbell-reverse-fly",
    "Dumbbell Reverse Fly",
    "dumbbell",
    "shoulders",
  ),
  exercise("one-arm-dumbbell-row", "One-Arm Dumbbell Row", "dumbbell", "back"),
  exercise(
    "dumbbell-bent-over-row",
    "Dumbbell Bent-Over Row",
    "dumbbell",
    "back",
  ),
  exercise(
    "chest-supported-dumbbell-row",
    "Chest-Supported Dumbbell Row",
    "dumbbell",
    "back",
  ),
  exercise("dumbbell-shrug", "Dumbbell Shrug", "dumbbell", "back"),
  exercise("dumbbell-biceps-curl", "Dumbbell Biceps Curl", "dumbbell", "arms"),
  exercise("hammer-curl", "Hammer Curl", "dumbbell", "arms"),
  exercise("concentration-curl", "Concentration Curl", "dumbbell", "arms"),
  exercise(
    "dumbbell-triceps-extension",
    "Dumbbell Triceps Extension",
    "dumbbell",
    "arms",
  ),
  exercise(
    "dumbbell-skull-crusher",
    "Dumbbell Skull Crusher",
    "dumbbell",
    "arms",
  ),
  exercise("dumbbell-kickback", "Dumbbell Kickback", "dumbbell", "arms"),
  exercise("bodyweight-squat", "Bodyweight Squat", "bodyweight", "legs"),
  exercise(
    "bulgarian-split-squat",
    "Bulgarian Split Squat",
    "bodyweight",
    "legs",
  ),
  exercise("reverse-lunge", "Reverse Lunge", "bodyweight", "legs"),
  exercise("forward-lunge", "Forward Lunge", "bodyweight", "legs"),
  exercise("glute-bridge", "Glute Bridge", "bodyweight", "glutes"),
  exercise(
    "single-leg-glute-bridge",
    "Single-Leg Glute Bridge",
    "bodyweight",
    "glutes",
  ),
  exercise("calf-raise", "Calf Raise", "bodyweight", "legs"),
  exercise("push-up", "Push-Up", "bodyweight", "chest"),
  exercise("knee-push-up", "Knee Push-Up", "bodyweight", "chest"),
  exercise("incline-push-up", "Incline Push-Up", "bodyweight", "chest"),
  exercise("decline-push-up", "Decline Push-Up", "bodyweight", "chest"),
  exercise("diamond-push-up", "Diamond Push-Up", "bodyweight", "arms"),
  exercise("pike-push-up", "Pike Push-Up", "bodyweight", "shoulders"),
  exercise("chair-dip", "Chair Dip", "bodyweight", "arms"),
  exercise("plank", "Plank", "bodyweight", "core"),
  exercise("side-plank", "Side Plank", "bodyweight", "core"),
  exercise("crunch", "Crunch", "bodyweight", "core"),
  exercise("bicycle-crunch", "Bicycle Crunch", "bodyweight", "core"),
  exercise("leg-raise", "Leg Raise", "bodyweight", "core"),
  exercise("dead-bug", "Dead Bug", "bodyweight", "core"),
  exercise("bird-dog", "Bird Dog", "bodyweight", "core"),
  exercise("mountain-climber", "Mountain Climber", "bodyweight", "full-body"),
  exercise("burpee", "Burpee", "bodyweight", "full-body"),
  exercise("superman", "Superman", "bodyweight", "back"),
];
